/**
 * UniPredict University Dataset
 * Comprehensive benchmark dataset for global universities covering US States & Global Regions
 */

const UNIVERSITIES_DATA = [
  {
    id: "cmu-cs",
    name: "Carnegie Mellon University",
    shortName: "CMU",
    location: "Pittsburgh, PA, USA",
    state: "Pennsylvania",
    region: "USA",
    tier: "Tier 1 (Elite)",
    worldRank: 5,
    acceptanceRate: 11.2,
    tuition: 61344,
    degreeLevels: ["MS", "PhD", "BS"],
    popularMajors: ["Computer Science", "Artificial Intelligence", "Data Science", "Software Engineering"],
    minGpa: 3.70,
    avgGpa: 3.91,
    minGreQuant: 167,
    avgGreQuant: 169,
    minGreVerbal: 156,
    avgGreVerbal: 161,
    minSat: 1510,
    avgSat: 1560,
    minToefl: 102,
    avgToefl: 110,
    minIelts: 7.5,
    researchWeight: 0.25,
    workExpWeight: 0.15,
    benchmarks: { gpa: 3.91, testScore: 98, research: 8.5, workExp: 7.5, leadership: 8.0, sopLor: 9.0 },
    description: "World-renowned for School of Computer Science, AI, and Robotics with rigorous technical standards."
  },
  {
    id: "mit-cs",
    name: "Massachusetts Institute of Technology",
    shortName: "MIT",
    location: "Cambridge, MA, USA",
    state: "Massachusetts",
    region: "USA",
    tier: "Tier 1 (Elite)",
    worldRank: 1,
    acceptanceRate: 6.7,
    tuition: 59750,
    degreeLevels: ["MS", "PhD", "BS"],
    popularMajors: ["Computer Science", "Electrical Engineering", "Data Science", "Artificial Intelligence"],
    minGpa: 3.85,
    avgGpa: 3.96,
    minGreQuant: 168,
    avgGreQuant: 170,
    minGreVerbal: 158,
    avgGreVerbal: 163,
    minSat: 1540,
    avgSat: 1580,
    minToefl: 105,
    avgToefl: 112,
    minIelts: 8.0,
    researchWeight: 0.30,
    workExpWeight: 0.10,
    benchmarks: { gpa: 3.96, testScore: 99, research: 9.5, workExp: 7.0, leadership: 8.5, sopLor: 9.5 },
    description: "Global pinnacle of engineering and innovation with ultra-selective admissions criteria."
  },
  {
    id: "stanford-eng",
    name: "Stanford University",
    shortName: "Stanford",
    location: "Stanford, CA, USA",
    state: "California",
    region: "USA",
    tier: "Tier 1 (Elite)",
    worldRank: 3,
    acceptanceRate: 7.1,
    tuition: 62484,
    degreeLevels: ["MS", "PhD", "BS"],
    popularMajors: ["Computer Science", "Artificial Intelligence", "Data Science"],
    minGpa: 3.80,
    avgGpa: 3.94,
    minGreQuant: 167,
    avgGreQuant: 169,
    minGreVerbal: 157,
    avgGreVerbal: 162,
    minSat: 1520,
    avgSat: 1570,
    minToefl: 104,
    avgToefl: 111,
    minIelts: 7.5,
    researchWeight: 0.25,
    workExpWeight: 0.20,
    benchmarks: { gpa: 3.94, testScore: 98, research: 9.0, workExp: 8.5, leadership: 9.0, sopLor: 9.2 },
    description: "Heart of Silicon Valley technology entrepreneurship, emphasizing research impact and leadership."
  },
  {
    id: "ucb-cs",
    name: "University of California, Berkeley",
    shortName: "UC Berkeley",
    location: "Berkeley, CA, USA",
    state: "California",
    region: "USA",
    tier: "Tier 1 (Elite)",
    worldRank: 8,
    acceptanceRate: 14.5,
    tuition: 44008,
    degreeLevels: ["MS", "PhD", "BS"],
    popularMajors: ["Computer Science", "Electrical Engineering", "Data Science"],
    minGpa: 3.65,
    avgGpa: 3.88,
    minGreQuant: 165,
    avgGreQuant: 168,
    minGreVerbal: 155,
    avgGreVerbal: 160,
    minSat: 1470,
    avgSat: 1530,
    minToefl: 100,
    avgToefl: 108,
    minIelts: 7.5,
    researchWeight: 0.28,
    workExpWeight: 0.12,
    benchmarks: { gpa: 3.88, testScore: 96, research: 8.8, workExp: 7.2, leadership: 7.8, sopLor: 8.8 },
    description: "Premier public research university renowned for foundational algorithms and systems computing."
  },
  {
    id: "columbia-cs",
    name: "Columbia University",
    shortName: "Columbia",
    location: "New York, NY, USA",
    state: "New York",
    region: "USA",
    tier: "Tier 1 (Elite)",
    worldRank: 11,
    acceptanceRate: 11.5,
    tuition: 63500,
    degreeLevels: ["MS", "PhD", "BS"],
    popularMajors: ["Computer Science", "Machine Learning", "Financial Engineering"],
    minGpa: 3.70,
    avgGpa: 3.89,
    minGreQuant: 166,
    avgGreQuant: 168,
    minGreVerbal: 156,
    avgGreVerbal: 160,
    minSat: 1490,
    avgSat: 1540,
    minToefl: 101,
    avgToefl: 109,
    minIelts: 7.5,
    researchWeight: 0.22,
    workExpWeight: 0.18,
    benchmarks: { gpa: 3.89, testScore: 96, research: 8.2, workExp: 7.8, leadership: 8.2, sopLor: 8.9 },
    description: "Ivy League research powerhouse located in Manhattan with top tech & finance recruiting."
  },
  {
    id: "gatech-cs",
    name: "Georgia Institute of Technology",
    shortName: "Georgia Tech",
    location: "Atlanta, GA, USA",
    state: "Georgia",
    region: "USA",
    tier: "Tier 2 (Top Tier)",
    worldRank: 16,
    acceptanceRate: 17.1,
    tuition: 31370,
    degreeLevels: ["MS", "PhD", "BS"],
    popularMajors: ["Computer Science", "Data Analytics", "Cybersecurity"],
    minGpa: 3.50,
    avgGpa: 3.79,
    minGreQuant: 163,
    avgGreQuant: 166,
    minGreVerbal: 153,
    avgGreVerbal: 158,
    minSat: 1430,
    avgSat: 1490,
    minToefl: 100,
    avgToefl: 105,
    minIelts: 7.5,
    researchWeight: 0.20,
    workExpWeight: 0.20,
    benchmarks: { gpa: 3.79, testScore: 92, research: 7.5, workExp: 8.0, leadership: 7.5, sopLor: 8.2 },
    description: "Engineering powerhouse offering top-ranked master's programs with excellent ROI."
  },
  {
    id: "uiuc-cs",
    name: "University of Illinois Urbana-Champaign",
    shortName: "UIUC",
    location: "Urbana, IL, USA",
    state: "Illinois",
    region: "USA",
    tier: "Tier 2 (Top Tier)",
    worldRank: 19,
    acceptanceRate: 19.3,
    tuition: 36000,
    degreeLevels: ["MS", "PhD", "BS"],
    popularMajors: ["Computer Science", "Software Engineering", "Data Science"],
    minGpa: 3.45,
    avgGpa: 3.76,
    minGreQuant: 162,
    avgGreQuant: 165,
    minGreVerbal: 152,
    avgGreVerbal: 157,
    minSat: 1410,
    avgSat: 1480,
    minToefl: 96,
    avgToefl: 104,
    minIelts: 7.0,
    researchWeight: 0.22,
    workExpWeight: 0.15,
    benchmarks: { gpa: 3.76, testScore: 90, research: 7.8, workExp: 7.2, leadership: 7.0, sopLor: 8.0 },
    description: "Historical pioneer in supercomputing, web browsers, and high-performance software engineering."
  },
  {
    id: "uw-cs",
    name: "University of Washington",
    shortName: "UW",
    location: "Seattle, WA, USA",
    state: "Washington",
    region: "USA",
    tier: "Tier 2 (Top Tier)",
    worldRank: 18,
    acceptanceRate: 18.2,
    tuition: 39500,
    degreeLevels: ["MS", "PhD", "BS"],
    popularMajors: ["Computer Science", "Human-Computer Interaction", "Data Science"],
    minGpa: 3.55,
    avgGpa: 3.82,
    minGreQuant: 164,
    avgGreQuant: 167,
    minGreVerbal: 154,
    avgGreVerbal: 159,
    minSat: 1440,
    avgSat: 1500,
    minToefl: 98,
    avgToefl: 106,
    minIelts: 7.0,
    researchWeight: 0.24,
    workExpWeight: 0.18,
    benchmarks: { gpa: 3.82, testScore: 93, research: 8.1, workExp: 7.6, leadership: 7.4, sopLor: 8.3 },
    description: "Paul G. Allen School of CS with direct ties to Amazon, Microsoft, and Pacific Northwest tech hubs."
  },
  {
    id: "umich-cs",
    name: "University of Michigan",
    shortName: "UMich",
    location: "Ann Arbor, MI, USA",
    state: "Michigan",
    region: "USA",
    tier: "Tier 2 (Top Tier)",
    worldRank: 22,
    acceptanceRate: 20.1,
    tuition: 52000,
    degreeLevels: ["MS", "PhD", "BS"],
    popularMajors: ["Computer Science", "Robotics", "Data Science"],
    minGpa: 3.50,
    avgGpa: 3.78,
    minGreQuant: 163,
    avgGreQuant: 166,
    minGreVerbal: 153,
    avgGreVerbal: 158,
    minSat: 1420,
    avgSat: 1490,
    minToefl: 97,
    avgToefl: 105,
    minIelts: 7.0,
    researchWeight: 0.22,
    workExpWeight: 0.16,
    benchmarks: { gpa: 3.78, testScore: 91, research: 7.6, workExp: 7.4, leadership: 7.5, sopLor: 8.1 },
    description: "Top public institution with world-class engineering, robotics, and cross-disciplinary research."
  },
  {
    id: "nyu-tandon",
    name: "New York University (Tandon)",
    shortName: "NYU Tandon",
    location: "New York, NY, USA",
    state: "New York",
    region: "USA",
    tier: "Tier 3 (High Match)",
    worldRank: 35,
    acceptanceRate: 32.4,
    tuition: 58160,
    degreeLevels: ["MS", "BS"],
    popularMajors: ["Computer Science", "Computer Engineering", "Data Science"],
    minGpa: 3.20,
    avgGpa: 3.58,
    minGreQuant: 158,
    avgGreQuant: 163,
    minGreVerbal: 150,
    avgGreVerbal: 154,
    minSat: 1370,
    avgSat: 1440,
    minToefl: 90,
    avgToefl: 101,
    minIelts: 7.0,
    researchWeight: 0.15,
    workExpWeight: 0.25,
    benchmarks: { gpa: 3.58, testScore: 84, research: 6.0, workExp: 7.8, leadership: 7.2, sopLor: 7.8 },
    description: "Dynamic urban campus located in Brooklyn Tech Triangle with strong industry tie-ups in NYC."
  },
  {
    id: "neu-cs",
    name: "Northeastern University",
    shortName: "Northeastern",
    location: "Boston, MA, USA",
    state: "Massachusetts",
    region: "USA",
    tier: "Tier 3 (High Match)",
    worldRank: 42,
    acceptanceRate: 34.8,
    tuition: 54500,
    degreeLevels: ["MS", "BS"],
    popularMajors: ["Computer Science", "Information Systems", "Data Architecture"],
    minGpa: 3.10,
    avgGpa: 3.52,
    minGreQuant: 157,
    avgGreQuant: 162,
    minGreVerbal: 149,
    avgGreVerbal: 153,
    minSat: 1350,
    avgSat: 1420,
    minToefl: 88,
    avgToefl: 98,
    minIelts: 6.5,
    researchWeight: 0.10,
    workExpWeight: 0.35,
    benchmarks: { gpa: 3.52, testScore: 82, research: 5.5, workExp: 8.5, leadership: 7.0, sopLor: 7.5 },
    description: "Famous for its Co-op internship model offering full-time corporate experience prior to graduation."
  },
  {
    id: "tamu-eng",
    name: "Texas A&M University",
    shortName: "TAMU",
    location: "College Station, TX, USA",
    state: "Texas",
    region: "USA",
    tier: "Tier 3 (High Match)",
    worldRank: 55,
    acceptanceRate: 48.5,
    tuition: 28500,
    degreeLevels: ["MS", "PhD", "BS"],
    popularMajors: ["Computer Engineering", "Computer Science", "Electrical Engineering"],
    minGpa: 3.00,
    avgGpa: 3.45,
    minGreQuant: 155,
    avgGreQuant: 160,
    minGreVerbal: 148,
    avgGreVerbal: 152,
    minSat: 1300,
    avgSat: 1380,
    minToefl: 85,
    avgToefl: 95,
    minIelts: 6.5,
    researchWeight: 0.15,
    workExpWeight: 0.20,
    benchmarks: { gpa: 3.45, testScore: 78, research: 5.8, workExp: 7.0, leadership: 6.8, sopLor: 7.2 },
    description: "Major research institution with affordable tuition, massive alumni network, and high admit rate."
  },
  {
    id: "asu-cs",
    name: "Arizona State University",
    shortName: "ASU",
    location: "Tempe, AZ, USA",
    state: "Arizona",
    region: "USA",
    tier: "Tier 3 (High Match)",
    worldRank: 120,
    acceptanceRate: 64.0,
    tuition: 32000,
    degreeLevels: ["MS", "BS"],
    popularMajors: ["Computer Science", "Software Engineering", "Information Technology"],
    minGpa: 3.00,
    avgGpa: 3.35,
    minGreQuant: 152,
    avgGreQuant: 157,
    minGreVerbal: 146,
    avgGreVerbal: 150,
    minSat: 1220,
    avgSat: 1300,
    minToefl: 80,
    avgToefl: 90,
    minIelts: 6.5,
    researchWeight: 0.08,
    workExpWeight: 0.22,
    benchmarks: { gpa: 3.35, testScore: 72, research: 4.5, workExp: 6.8, leadership: 6.2, sopLor: 7.0 },
    description: "Top innovative public university known for inclusive admissions and flexible tech programs."
  },
  {
    id: "oxford-cs",
    name: "University of Oxford",
    shortName: "Oxford",
    location: "Oxford, UK",
    state: "Oxfordshire",
    region: "UK",
    tier: "Tier 1 (Elite)",
    worldRank: 2,
    acceptanceRate: 10.5,
    tuition: 42000,
    degreeLevels: ["MSc", "DPhil", "BA"],
    popularMajors: ["Computer Science", "Advanced Computer Science", "AI & ML"],
    minGpa: 3.80,
    avgGpa: 3.93,
    minGreQuant: 166,
    avgGreQuant: 168,
    minGreVerbal: 158,
    avgGreVerbal: 162,
    minSat: 1510,
    avgSat: 1550,
    minToefl: 110,
    avgToefl: 115,
    minIelts: 7.5,
    researchWeight: 0.35,
    workExpWeight: 0.10,
    benchmarks: { gpa: 3.93, testScore: 97, research: 9.2, workExp: 6.5, leadership: 7.5, sopLor: 9.6 },
    description: "World's oldest English-speaking university with intense academic rigor and tutorial supervision."
  },
  {
    id: "cambridge-cs",
    name: "University of Cambridge",
    shortName: "Cambridge",
    location: "Cambridge, UK",
    state: "Cambridgeshire",
    region: "UK",
    tier: "Tier 1 (Elite)",
    worldRank: 4,
    acceptanceRate: 11.8,
    tuition: 44500,
    degreeLevels: ["MPhil", "PhD", "BA"],
    popularMajors: ["Computer Science", "Machine Learning", "Advanced Computer Science"],
    minGpa: 3.78,
    avgGpa: 3.92,
    minGreQuant: 166,
    avgGreQuant: 168,
    minGreVerbal: 157,
    avgGreVerbal: 161,
    minSat: 1500,
    avgSat: 1540,
    minToefl: 108,
    avgToefl: 114,
    minIelts: 7.5,
    researchWeight: 0.35,
    workExpWeight: 0.10,
    benchmarks: { gpa: 3.92, testScore: 97, research: 9.1, workExp: 6.5, leadership: 7.4, sopLor: 9.4 },
    description: "Historic computing research hub where Alan Turing studied, leading theoretical & applied CS."
  },
  {
    id: "imperial-cs",
    name: "Imperial College London",
    shortName: "Imperial",
    location: "London, UK",
    state: "Greater London",
    region: "UK",
    tier: "Tier 1 (Elite)",
    worldRank: 6,
    acceptanceRate: 12.4,
    tuition: 43000,
    degreeLevels: ["MSc", "PhD", "BSc"],
    popularMajors: ["Computing", "Artificial Intelligence", "Software Engineering"],
    minGpa: 3.70,
    avgGpa: 3.88,
    minGreQuant: 165,
    avgGreQuant: 168,
    minGreVerbal: 155,
    avgGreVerbal: 160,
    minSat: 1480,
    avgSat: 1530,
    minToefl: 105,
    avgToefl: 112,
    minIelts: 7.5,
    researchWeight: 0.30,
    workExpWeight: 0.15,
    benchmarks: { gpa: 3.88, testScore: 95, research: 8.6, workExp: 7.0, leadership: 7.3, sopLor: 9.0 },
    description: "London's flagship STEM institution focused exclusively on science, engineering, and medicine."
  },
  {
    id: "eth-zurich",
    name: "ETH Zurich",
    shortName: "ETH Zurich",
    location: "Zurich, Switzerland",
    state: "Zurich",
    region: "Europe",
    tier: "Tier 1 (Elite)",
    worldRank: 7,
    acceptanceRate: 18.0,
    tuition: 1600,
    degreeLevels: ["MSc", "PhD", "BSc"],
    popularMajors: ["Computer Science", "Data Science", "Cybersecurity", "Robotics"],
    minGpa: 3.60,
    avgGpa: 3.85,
    minGreQuant: 165,
    avgGreQuant: 168,
    minGreVerbal: 154,
    avgGreVerbal: 158,
    minSat: 1450,
    avgSat: 1510,
    minToefl: 100,
    avgToefl: 108,
    minIelts: 7.0,
    researchWeight: 0.30,
    workExpWeight: 0.10,
    benchmarks: { gpa: 3.85, testScore: 95, research: 8.5, workExp: 6.8, leadership: 7.0, sopLor: 8.8 },
    description: "Continental Europe's top engineering university featuring ultra-low tuition and world-class labs."
  },
  {
    id: "tum-cs",
    name: "Technical University of Munich",
    shortName: "TUM",
    location: "Munich, Germany",
    state: "Bavaria",
    region: "Europe",
    tier: "Tier 2 (Top Tier)",
    worldRank: 28,
    acceptanceRate: 22.0,
    tuition: 3000,
    degreeLevels: ["MSc", "BSc"],
    popularMajors: ["Informatics", "Data Engineering", "Robotics & AI"],
    minGpa: 3.40,
    avgGpa: 3.72,
    minGreQuant: 160,
    avgGreQuant: 164,
    minGreVerbal: 150,
    avgGreVerbal: 155,
    minSat: 1380,
    avgSat: 1460,
    minToefl: 88,
    avgToefl: 98,
    minIelts: 6.5,
    researchWeight: 0.20,
    workExpWeight: 0.18,
    benchmarks: { gpa: 3.72, testScore: 88, research: 7.2, workExp: 7.0, leadership: 6.8, sopLor: 7.8 },
    description: "Germany's leading technical university with strong industry ties to BMW, Siemens, and SAP."
  },
  {
    id: "utoronto-cs",
    name: "University of Toronto",
    shortName: "U of T",
    location: "Toronto, ON, Canada",
    state: "Ontario",
    region: "Canada",
    tier: "Tier 2 (Top Tier)",
    worldRank: 21,
    acceptanceRate: 23.5,
    tuition: 45000,
    degreeLevels: ["MSc", "PhD", "BSc"],
    popularMajors: ["Computer Science", "Applied Computing", "Artificial Intelligence"],
    minGpa: 3.50,
    avgGpa: 3.80,
    minGreQuant: 162,
    avgGreQuant: 166,
    minGreVerbal: 152,
    avgGreVerbal: 156,
    minSat: 1420,
    avgSat: 1490,
    minToefl: 93,
    avgToefl: 104,
    minIelts: 7.0,
    researchWeight: 0.25,
    workExpWeight: 0.15,
    benchmarks: { gpa: 3.80, testScore: 91, research: 8.0, workExp: 7.2, leadership: 7.2, sopLor: 8.4 },
    description: "Canada's flagship institution, pioneer in deep learning and artificial intelligence."
  },
  {
    id: "nus-cs",
    name: "National University of Singapore",
    shortName: "NUS",
    location: "Singapore",
    state: "Singapore",
    region: "Asia",
    tier: "Tier 1 (Elite)",
    worldRank: 8,
    acceptanceRate: 15.0,
    tuition: 29800,
    degreeLevels: ["MSc", "PhD", "BSc"],
    popularMajors: ["Computer Science", "Computing", "Business Analytics"],
    minGpa: 3.65,
    avgGpa: 3.86,
    minGreQuant: 165,
    avgGreQuant: 167,
    minGreVerbal: 154,
    avgGreVerbal: 158,
    minSat: 1460,
    avgSat: 1520,
    minToefl: 95,
    avgToefl: 105,
    minIelts: 7.0,
    researchWeight: 0.22,
    workExpWeight: 0.18,
    benchmarks: { gpa: 3.86, testScore: 95, research: 8.2, workExp: 7.5, leadership: 7.6, sopLor: 8.6 },
    description: "Asia's leading technology university providing state-of-the-art research facilities."
  },
  {
    id: "iisc-cs",
    name: "Indian Institute of Science",
    shortName: "IISc Bangalore",
    location: "Bengaluru, KA, India",
    state: "Karnataka",
    region: "India",
    tier: "Tier 1 (Elite)",
    worldRank: 155,
    acceptanceRate: 5.2,
    tuition: 1200,
    degreeLevels: ["MTech", "PhD", "BS"],
    popularMajors: ["Computer Science", "Computational Data Science", "Artificial Intelligence"],
    minGpa: 3.60,
    avgGpa: 3.85,
    minGreQuant: 166,
    avgGreQuant: 169,
    minGreVerbal: 154,
    avgGreVerbal: 158,
    minSat: 1450,
    avgSat: 1510,
    minToefl: 90,
    avgToefl: 100,
    minIelts: 6.5,
    researchWeight: 0.35,
    workExpWeight: 0.10,
    benchmarks: { gpa: 3.85, testScore: 96, research: 9.0, workExp: 6.0, leadership: 6.5, sopLor: 8.5 },
    description: "India's premier institute for advanced scientific and technological research."
  },
  {
    id: "unimelb-cs",
    name: "University of Melbourne",
    shortName: "UniMelb",
    location: "Melbourne, VIC, Australia",
    state: "Victoria",
    region: "Australia",
    tier: "Tier 2 (Top Tier)",
    worldRank: 14,
    acceptanceRate: 35.0,
    tuition: 38000,
    degreeLevels: ["MCIS", "PhD", "BSc"],
    popularMajors: ["Computer Science", "Information Technology", "Software Engineering"],
    minGpa: 3.25,
    avgGpa: 3.60,
    minGreQuant: 158,
    avgGreQuant: 163,
    minGreVerbal: 150,
    avgGreVerbal: 154,
    minSat: 1350,
    avgSat: 1430,
    minToefl: 85,
    avgToefl: 96,
    minIelts: 6.5,
    researchWeight: 0.15,
    workExpWeight: 0.20,
    benchmarks: { gpa: 3.60, testScore: 84, research: 6.5, workExp: 7.2, leadership: 7.0, sopLor: 7.8 },
    description: "Australia's top university located in Melbourne, offering modern tech infrastructure and industry links."
  }
];
